version: "2"

services:
  rsyslog:
    build: rsyslog
    volumes:
      - /var/log/journal:/var/log/journal:ro
      - /etc/machine-id:/etc/machine-id
      - ./rsyslog.conf:/etc/rsyslog.conf
    command: rsyslogd -n

  loggenerator:
    image: fedora
    volumes:
      - ./log-generator.sh:/log-generator.sh
    command: [sh, /log-generator.sh]
